AllYarnsAreBeautiful/ayab-firmware

- .travis.yml
- README
- README.md
- ayab.ino
- ayab_hw_test.inox
- beeper.cpp
- beeper.h
- debug.h
- encoders.cpp
- encoders.h
- knitter.cpp
- knitter.h
- libraries/Alt_MCP23008/Alt_MCP23008.cpp
- libraries/Alt_MCP23008/Alt_MCP23008.h
- libraries/Alt_MCP23008/README.txt
- settings.h
- solenoids.cpp
- solenoids.h
These prior changes were added to the V0.90 branch in September, but perhaps they should be pulled into the master branch. 
Comments and disagreement welcome, but prefer to resolve this so that we have fewer simultaneous branches. (We're working on other improvements that we'd like to add.)
> Pull V0.90 into master

- README.md
After having helped out with updating AYAB firmware I thought I would add the instructions that would have saved me a few minutes.
> Add firmware update instructions to readme.

- .clang-format
- ayab.ino
- ayab_hw_test.inox
- beeper.cpp
- beeper.h
- debug.h
- encoders.cpp
- encoders.h
- knitter.cpp
- knitter.h
- settings.h
- solenoids.cpp
- solenoids.h
Preliminary implementation of #20
> Format with clang-format

- .gitignore
- solenoids.cpp
- test/CMakeLists.txt
- test/test_all.cpp
- test/test_beeper.cpp
- test/test_encoders.cpp
- Added unit tests for beeper, 100% line and branch coverage
- Ran clang-format on test directory (I have a commit hook for this now, happy to share it)
- Removed unintentional changes to .gitignore
- Removed cruft from CMakeLists.txt, the cxx standard flag is only supported in cmake 3.1+
- Reverted include path change that doesn't work well with the Arduino build system
- I finally figured out how to build with build.sh locally after taking a peek at .travis.yml, maybe that setup should be described in some documentation somewhere?
> Add unit tests for beeper

- .pre-commit-config.yaml
- README.md
- Document setting up to run ./build.sh
- Document commit and push hooks
> Document development environment

- doc/finite_state_machine.md
- src/ayab/com.cpp
- src/ayab/com.h
- src/ayab/fsm.cpp
- src/ayab/fsm.h
- src/ayab/global_com.cpp
- src/ayab/global_knitter.cpp
- src/ayab/global_tester.cpp
- src/ayab/knitter.cpp
- src/ayab/knitter.h
- src/ayab/tester.cpp
- src/ayab/tester.h
- test/mocks/com_mock.cpp
- test/mocks/com_mock.h
- test/mocks/knitter_mock.cpp
- test/mocks/knitter_mock.h
- test/mocks/tester_mock.cpp
- test/mocks/tester_mock.h
- test/test_com.cpp
- test/test_fsm.cpp
- test/test_knitter.cpp
- test/test_solenoids.cpp
- test/test_tester.cpp
Referencing https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/28
> Add error state. Remove some FRIEND_TESTs.

- README.md
- build.sh
Adds mac install instructions to the README and a minor fix to fetch the correct number of processors in the build file.
> Update documentation and build to work on macos

- src/ayab/encoders.cpp
- src/ayab/encoders.h
- src/ayab/knitter.cpp
- src/ayab/knitter.h
- test/test_encoders.cpp
- test/test_fsm.cpp
- test/test_knitter.cpp
This works reliably. I can't test the right hall sensor because my machine has hardware issues but I can take a stab at it if y'all want.
There may be a one needle alignment issue but I'll follow up and correct that later.
> Garter carriage detection from the left hall sensor

- test/test_encoders.cpp
This addresses #54 . I'm pretty wary of a couple of these changes, need someone to review- I'll leave comments.
> Fix encoder tests

- test/mocks/beeper_mock.cpp
- test/mocks/com_mock.cpp
- test/mocks/encoders_mock.cpp
- test/mocks/fsm_mock.cpp
- test/mocks/knitter_mock.cpp
- test/mocks/solenoids_mock.cpp
- test/mocks/tester_mock.cpp
Change all uses of NULL to nullptr in line with modern usage.
> Fix inconsistent use of NULL/nullptr

- .gitmodules
- build.sh
- src/ayab/Makefile
- src/ayab/board.h
- src/ayab/solenoids.cpp
- src/ayab/solenoids.h
- static_analysis.sh
- test/CMakeLists.txt
Addressing https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/72
We can remove the submodule SoftI2CMaster.
> do not build firmware for Arduino Mega

- src/ayab/fsm.cpp
- src/ayab/fsm.h
- test/test_fsm.cpp
- test/test_knitter.cpp
> add Fsm method to explicitly handle dispatch for state `s_wait_for_machine`

- .github/workflows/build_firmware.yml
> build doxygen source file documentation and deploy to github pages

- src/ayab/com.cpp
- src/ayab/com.h
- test/CMakeLists.txt
> remove AYAB_ENABLE_CRC compile option

- src/ayab/fsm.cpp
- src/ayab/fsm.h
- src/ayab/knitter.cpp
- src/ayab/tester.cpp
- test/test_com.cpp
- test/test_fsm.cpp
- test/test_knitter.cpp
- test/test_tester.cpp
> change enum Opstate to enum class Opstate

- src/ayab/encoders.cpp
- src/ayab/encoders.h
- src/ayab/knitter.cpp
- test/test_encoders.cpp
- test/test_knitter.cpp
> change enum BeltShift to enum class BeltShift

- .github/workflows/build_firmware.yml
> Deploy docs only on release

- src/ayab/encoders.h
> add comment about justification for GARTER_SLOP constant

- Doxyfile
fixes https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/89#issuecomment-1620754330
> Change doxygen html folder to '/docs' for gh pages

- .github/workflows/build_firmware.yml
Allows initial 'v' and suffix.
> check tag for compliance with semver 2.0

- src/ayab/encoders.cpp
- src/ayab/encoders.h
- test/test_knitter.cpp
https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/4
Fixes 270 alignment with the original carriage.
> Update 270 values and add an early out

- .github/workflows/build_firmware.yml
- sonar-project.properties
Add SonarCloud build analysis acc. to https://sonarcloud.io/project/configuration/GitHubActions?id=AllYarnsAreBeautiful_ayab-firmware
> Add SonarCloud analysis via CI

- src/ayab/encoders.cpp
Couple of small changes which I believe are required by C++20.
> Update encoders.cpp to remove code smell

- src/ayab/com.cpp
- src/ayab/encoders.cpp
- src/ayab/tester.cpp
> remove redundant casts, replace redundant types with auto

- .github/workflows/archive_build.yml
- src/ayab/com.cpp
- src/ayab/com.h
- src/ayab/encoders.cpp
- src/ayab/encoders.h
- src/ayab/fsm.cpp
- src/ayab/fsm.h
- src/ayab/global_com.cpp
- src/ayab/global_encoders.cpp
- src/ayab/knitter.cpp
- src/ayab/knitter.h
- src/ayab/tester.cpp
- test/mocks/com_mock.cpp
- test/mocks/com_mock.h
- test/test_com.cpp
- test/test_knitter.cpp
- test/test_tester.cpp
Migrate from `enum ErrorCode` to `enum class ErrorCode` and do some other cleaning up.
> Migrate from `enum` to `enum class`

- src/ayab/encoders.cpp
- src/ayab/encoders.h
- src/ayab/knitter.cpp
- test/test_fsm.cpp
- test/test_knitter.cpp
Speeds up code slightly in ISRs
> Minor changes to encoders

- src/ayab/tester.cpp
Removes some potential security issues.
> Use `snprintf` in tester.cpp

- src/ayab/com.cpp
- src/ayab/com.h
- src/ayab/fsm.cpp
- src/ayab/fsm.h
- src/ayab/knitter.cpp
- src/ayab/knitter.h
- src/ayab/tester.cpp
- test/test_com.cpp
- test/test_knitter.cpp
- test/test_tester.cpp
also migrate enum AYAB_API to enum class
> Change error codes to lower case consistent with other enums

- src/ayab/knitter.cpp
> Move to state Init after finishing Knit operation

- lib/crc8/crc8.cpp
- lib/crc8/crc8.h
- lib/platform/common/packetSerial/hal_packetserial.h
- fix typo (forgot to modify the header file while fixing the typo in crc8.cpp)
- some doc/code improvements
> coderabbitai suggested improvements
