AllYarnsAreBeautiful/ayab-firmware

.gitignore
encoders.cpp
encoders.h
settings.h
test/CMakeLists.txt
test/README.md
test/arduino_mock/CMakeLists.txt
test/test.sh
test/test_all.cpp
test/test_encoders.cpp

Added tests for encoders, line coverage is 93% and branch coverage is 75%, this can obviously be improved.
I made tiny changes to the code itself to make it easier to test (see changes in settings.h and encoders.cpp/encoders.h).
The test/README.md file should guide developers in setting up the test environment and running tests.

Add unit tests for encoders

---

CONTRIBUTING.md
src/ayab/encoders.cpp

This pulls in the fix from #48 as well as the `contributing.md` document. I chose to cherry-pick over a merge or rebase, as the changes from a489694 cause a whole heap of merge conflicts.
If one instead wishes to perform a rebase or merge to obtain these changes, reverting a489694 on master beforehand avoids the majority of merge conflict madness. That flow for me was pretty simple, with almost no issues:
```
git switch master
git revert a489694
git switch v1.0-dev
git rebase master
```

Update v1.0-dev branch with recent changes from main branch

---

.github/workflows/run_tests.yml
src/ayab/solenoids.cpp
test/CMakeLists.txt
test/arduino_mock/CMakeLists.txt

This addresses the test running issues brought up in #54 but it does _NOT_ address failing tests.  
If anyone has access to the [bt-trx fork of `arduino-mock`](https://github.com/bt-trx/arduino-mock) then updating that might be more sensible than using my new fork here- I only added minimal changes to update the gtest dependency version.
This PR also adds some high-level reporting for test failures, both in PRs and the actions interface. Hopefully this helps make it easier to identify regressions and fix issues.

Fix test running, add Test Results parsing

---

test/test_tester.cpp

This shuts up a lot of noisy test for now, but ultimately we probably need to switch `packetserial` over to using the mocking approach that's leveraged elsewhere.

Disable bad serial test

---

.github/workflows/build_firmware.yml

This lets github action builds get stored, so folks can download test versions of firmware without needing a local build environment.

update builder, add archive

---

.github/workflows/build_firmware.yml

Creates a release and uploads artifacts from build/*.hex
Job is activated when a tag is pushed that begins with 'v' or 'test'
Something like this is necessary so that the desktop software can grab the build assets from the latest release.

v1.0 dev workflow job to create release assets 

---

src/ayab/tester.cpp

Change message to 0x31 0x32 0x33 from 0x01 0x02 0x03 so that the characters are visible in the console
Desktop PR https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/483

Change HW test message

---

src/ayab/com.h

Token values in APIv6 are currently documented in https://github.com/t0mpr1c3/ayab-manual/blob/patch-4/docs/API.md
See https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/487 for equivalent changes in desktop

change Token values consistent with APIv6

---

src/ayab/solenoids.cpp
test/test_solenoids.cpp

Addressing https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/74

remove redundant preprocessor instructions in solenoids.cpp and test_solenoids.cpp

---

src/ayab/com.cpp
src/ayab/com.h
src/ayab/fsm.h

An extra byte is added to the message after the success/error byte indicating the FSM state.
Proposed in https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/28.
Change to API documentation: https://github.com/AllYarnsAreBeautiful/ayab-manual/pull/21
If the PR is approved I can go back and add tests to improve the coverage.

change Com::send_indState

---

src/ayab/beeper.cpp
src/ayab/solenoids.h
test/test_beeper.cpp
test/test_com.cpp
test/test_solenoids.cpp

Comment out some calls to SerialMock methods.
Rewrite a couple of tests of Com::h_reqInit. which still need SerialPacket to be mocked.
Replace some constant values with named constants in test_beeper.cpp.

some tweaks to test scripts

---

build.sh

Removes some legacy code: hardware testing is done in software now, we don't do a separate firmware build.

do not need hw_test option in build.sh

---

.gitignore
platformio.ini
scripts/preBuild.py
src/ayab/com.cpp
src/ayab/com.h

Implements changes to report the firmware version in cnfInfo according to the current git tag.
- The git tag has to be in the format x.y.z, where x,y,z are 1-3 digits. (as defined by semver.org).
- In case the git tag does not match this format, 0.0.0 is used.
- In case there have been changes since the tag was applied (indicated by an appendix in the version string by `git describe --tags`, for example "1.0.0-4-gc5abe8c", the "dirty" flag is set to indicate that the software does as been altered.
Still to do (any help appreciated!):
```
payload[0] = cnfInfo_msgid;
payload[1] = API_VERSION;
payload[2] = FW_VERSION_MAJ;
payload[3] = FW_VERSION_MIN;
payload[4] = FW_VERSION_PATCH;
payload[5] = FW_VERSION_DIRTY;
```

Report git tag as fw version

---

src/ayab/encoders.cpp
src/ayab/encoders.h
src/ayab/knitter.cpp
src/ayab/knitter.h
src/ayab/solenoids.cpp
src/ayab/solenoids.h
test/test_knitter.cpp

Corresponding desktop PR: https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/571
In this PR:
- Updates to the 270 constants in encoders.h
- 114 needles -> 112 needles because the last needles don't pattern
- Set pixels even outside of the working area because the desktop software is now setting "flanking needles"
- Removed LED setting for the 270 when inside of working needles
- Disabled EOL beeper for 270 because it's causing problems setting flanking needles, we can revert this if the proposed beeper scheduling solves this problem.
- Unified calculatePixelAndSolenoid logic
- Updated tests

Make the 270 a first class citizen

---

.github/workflows/build_firmware.yml

SonarCloud analysis is disabled in forks and on pull requests from forks. The issue is that SONAR_TOKEN is only available in the main repo.
SonarCloud analysis remains activated in pull requests that originate in the main repo, and on push.
(I think what we really want for PR from forks is a `pull_request_target` event rather than `pull_request`: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)

Disable SonarCloud analysis in fork / on PR from fork

---

src/ayab/com.cpp
src/ayab/encoders.cpp
src/ayab/encoders.h
src/ayab/fsm.h
src/ayab/knitter.cpp
src/ayab/main.cpp
test/test_com.cpp
test/test_encoders.cpp
test/test_fsm.cpp
test/test_knitter.cpp
test/test_tester.cpp

Migrate from `enum Machine` to `enum class Machine`,  `enum Carriage` to `enum class Carriage`,  `enum Direction` to `enum class Direction`

Using enum class Machine/Carriage/Direction

---

src/ayab/com.cpp
src/ayab/com.h
test/test_com.cpp

Closes #171
Chopped out of the monster that is #154

Fix reqTest bug

---

src/ayab/encoders.h
src/ayab/knitter.cpp

Update offsets for G carriage on the 930
Make sure to calculate the first HALF_SOLENOID pixels when the lace carriage is selected.
Addresses: 
- https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/180
- https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/178

930 bug fixes for garter carriage alignment and lace carriage start selection

---

ayab.ino
encoders.cpp
encoders.h
hallsensor.cpp
hallsensor.h
knitter.cpp

Add support for G-carriage detection
For G-carriage, per brother doc, south-then-north transitions within 3 needles is detected (but not the other way around), when only one transition is detected (within 3 needles) then K or L is reported.
Tested on KH910 => couldn't test RHS detection due to the HW bug (and  commented out L75-L81 as a consequence but it should just work as well)

Add support for G-carriage detection

---

src/ayab/main.cpp

The classes that make up the AYAB firmware are currently dynamically allocated with `new` at the top level of `main.cpp`:
https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/e960ad4d9cd86daa4b3abbafad90de51ad102da5/src/ayab/main.cpp#L50-L56
Since these objects are allocated at the start of the program and never freed, there is no advantage to having them dynamically allocated. On the other hand, there are disadvantages:
- dynamically allocated objects can use a few more bytes for the memory allocator's bookkeeping;
- the memory used by these objects is not counted in the PlatformIO builder's statistics of RAM usage, that are printed after every build.
That last point in particular can hide the fact that the memory requirements for the firmware exceed the target microcontroller's …

Allocate class instances statically
